apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis-pv
  namespace: learn-k8s
  labels:
    type: local
spec:
  capacity:
    storage: 100Mi  # Adjust size as needed
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce  # Access mode
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /Users/ngocp/Documents/projects/kubernete/data/redis
    type: DirectoryOrCreate

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: nodejs-pv
  namespace: learn-k8s
  labels:
    type: local
spec:
  capacity:
    storage: 600Mi  # Adjust size as needed
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce  # Access mode
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/Users/ngocp/Documents/projects/kubernete/app"
    type: DirectoryOrCreate