apiVersion: v1
kind: Service
metadata:
  name: redis-master
  namespace: learn-k8s
  labels:
    app: redis
spec:
  ports:
  - port: 6379
    name: redis
  clusterIP: None
  selector:
    app: redis-master
---
apiVersion: v1
kind: Service
metadata:
  name: redis-slave
  namespace: learn-k8s
  labels:
    app: redis
spec:
  ports:
  - port: 6379
    name: redis
  clusterIP: None
  selector:
    app: redis-slave
