apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: learn-k8s
data:
  nginx.conf: |
    events {
      worker_connections 1024;
    }

    http {
      upstream nodejs-express-service {
        server nodejs-express-service:3000;
      }

      server {
        listen 80;

        location / {
          proxy_pass http://nodejs-express-service;
          proxy_set_header Host $host;
          proxy_set_header X-Real-IP $remote_addr;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
          proxy_set_header X-Forwarded-Proto $scheme;
        }
      }
    }

