apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginxwebserver
  namespace: learn-k8s
  labels:
    app: nginxwebserver
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginxwebserver
  template:
    metadata:
      labels:
        app: nginxwebserver
    spec:
      containers:
      - name: nginxwebserver
        image: nginx
        ports:
        - containerPort: 80
        volumeMounts:
        - name: config-volume
          mountPath: /etc/nginx/nginx.conf
          subPath: nginx.conf
      volumes:
      - name: config-volume
        configMap:
          name: nginx-config
          # items:
          # - key: nginx.conf
          #   path: nginx.conf
