apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-express-deployment
  namespace: learn-k8s
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodejs-express
  template:
    metadata:
      labels:
        app: nodejs-express
    spec:
      containers:
      - name: nodejs-express
        image: phann123/nodejs-express-app:latest0620
        ports:
        - containerPort: 3000
        volumeMounts:
          - name: nodejs-app-source
            mountPath: /usr/src/app
      volumes:
      - name: nodejs-app-source
        persistentVolumeClaim:
            claimName: nodejs-pvc  # Name of the PVC created earlier


---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nodejs-pv
spec:
  capacity:
    storage: 500Mb  # Adjust size as needed
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce  # Access mode
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /path/to/your/local/directory  # Path on your local machine

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nodejs-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mb  # Requested storage size, should match or be less than PV