apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-deployment
  namespace: learn-k8s
  labels:
    app: redis
spec:
  replicas: 2
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - image: redis
        imagePullPolicy: Always
        name: redis
        ports:
        - containerPort: 6379  # Corrected port to default Redis port
          protocol: TCP
        volumeMounts:
        - name: redis-data
          mountPath: /data  # Mounting the volume at /data where Redis stores data
      volumes:
      - name: redis-data
        persistentVolumeClaim:
          claimName: redis-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-pvc
  namespace: learn-k8s
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi