apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-deployment
  namespace: learn-k8s
  labels:
    app: redis
spec:
  replicas: 2
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - image: redis
        imagePullPolicy: Always
        name: redis-master
        ports:
          - containerPort: 6379
        volumeMounts:
          - name: redis-data
            mountPath: /data
      - image: redis
        imagePullPolicy: Always
        name: redis-slave
        command: ["redis-server", "--slaveof", "redis-master", "6379"]
        volumeMounts:
          - name: redis-data
            mountPath: /data
      volumes:
        - name: redis-data
          persistentVolumeClaim:
            claimName: redis-pvc  # Name of the PVC created earlier
---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-pvc
  namespace: learn-k8s
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi  # Requested storage size, should match or be less than PV
