apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: learn-k8s
data:
  nginx.conf: |
    user  nginx;
    worker_processes  1;

    error_log  /var/log/nginx/error.log warn;
    pid        /var/run/nginx.pid;

    events {
        worker_connections  1024;
    }

    http {
        server {
            listen 80;
            location / {
                proxy_pass http://nodejs-service:8080; # Assuming your Node.js service is named nodejs-service and listens on port 8080
                proxy_http_version 1.1;
                proxy_set_header Upgrade $http_upgrade;
                proxy_set_header Connection 'upgrade';
                proxy_set_header Host $host;
                proxy_cache_bypass $http_upgrade;
            }
        }
    }